apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: autoinstrumentation
spec:
  exporter:
    endpoint: http://$(OTEL_NODE_IP):4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1.00"
  env:
  - name: OTEL_NODE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
   
