apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  name: operator-cluster
  nodes:
  - role: control-plane
  - role: worker
  - role: worker% 